services:
  icm20948_imu_node:
    image: icm20948_imu_node:humble
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
      - I2C_GROUP_ID=988
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID /run.sh
